// packages/vue/src/UltimateGrid.vue
<script setup lang="ts">
/**
 * @ultimate-grid/vue — Vue 3 wrapper component for @ultimate-grid/core.
 *
 * Usage:
 *   import { UltimateGrid } from '@ultimate-grid/vue';
 *
 *   <UltimateGrid
 *     :column-defs="columnDefs"
 *     :row-data="rowData"
 *     selection-mode="multi"
 *     :row-height="36"
 *     :cell-renderer="customCellRenderer"
 *     @grid-ready="onGridReady"
 *     @sort-changed="onSortChanged"
 *     @filter-changed="onFilterChanged"
 *     @selection-changed="onSelectionChanged"
 *   />
 */
import { ref, onMounted, onUnmounted, watch } from 'vue';
import { createGrid } from '../../core/src/index.ts';
import type { RenderPipelineOptions } from '../../core/src/render/RenderPipeline.ts';
import type {
  ColumnDef,
  GridApi,
  GridOptions,
  GridEventMap,
} from '../../core/src/types.ts';

// ─── Props ────────────────────────────────────────────────────────────────────

const props = withDefaults(
  defineProps<{
    columnDefs: ColumnDef[];
    rowData?: unknown[];
    selectionMode?: GridOptions['selectionMode'];
    rowHeight?: number;
    cellRenderer?: RenderPipelineOptions['cellRenderer'];
    options?: Partial<GridOptions>;
  }>(),
  {
    selectionMode: 'multi',
  },
);

// ─── Emits ────────────────────────────────────────────────────────────────────

const emit = defineEmits<{
  gridReady:        [api: GridApi];
  rowDataChanged:   [e: GridEventMap['rowDataChanged']];
  sortChanged:      [e: GridEventMap['sortChanged']];
  filterChanged:    [e: GridEventMap['filterChanged']];
  selectionChanged: [e: GridEventMap['selectionChanged']];
  columnResized:    [e: GridEventMap['columnResized']];
  columnMoved:      [e: GridEventMap['columnMoved']];
  cellClicked:      [e: GridEventMap['cellClicked']];
  cellDoubleClicked:[e: GridEventMap['cellDoubleClicked']];
  activeCellChanged: [e: GridEventMap['activeCellChanged']];
}>();

// ─── Internal state ────────────────────────────────────────────────────────────

const containerRef = ref<HTMLDivElement | null>(null);
const apiRef        = ref<GridApi | null>(null);
let   unsubFns: Array<() => void> = [];

// ─── Mount / destroy helpers ──────────────────────────────────────────────────

function mountGrid(): void {
  if (!containerRef.value) return;

  unsubFns.forEach(fn => fn());
  unsubFns = [];
  if (apiRef.value) {
    apiRef.value.destroy();
    apiRef.value = null;
  }

  const api = createGrid({
    ...props.options,
    container:     containerRef.value,
    columnDefs:    props.columnDefs,
    rowData:       props.rowData ?? [],
    selectionMode: props.selectionMode ?? props.options?.selectionMode ?? 'multi',
    rowHeight:     props.rowHeight ?? props.options?.rowHeight,
    cellRenderer:  props.cellRenderer,
  });

  apiRef.value = api;

  unsubFns.push(
    api.on('rowDataChanged',    e => emit('rowDataChanged',   e)),
    api.on('sortChanged',       e => emit('sortChanged',      e)),
    api.on('filterChanged',     e => emit('filterChanged',    e)),
    api.on('selectionChanged',  e => emit('selectionChanged', e)),
    api.on('columnResized',     e => emit('columnResized',    e)),
    api.on('columnMoved',       e => emit('columnMoved',      e)),
    api.on('cellClicked',       e => emit('cellClicked',      e)),
    api.on('cellDoubleClicked', e => emit('cellDoubleClicked',e)),
    api.on('activeCellChanged',  e => emit('activeCellChanged', e)),
  );

  emit('gridReady', api);
}

// ─── Lifecycle ────────────────────────────────────────────────────────────────

onMounted(() => mountGrid());

// Remount when structural props change
watch(() => [props.columnDefs, props.selectionMode, props.rowHeight] as const, () => {
  mountGrid();
});

// Sync rowData without remounting
watch(() => props.rowData, (newVal) => {
  if (apiRef.value && newVal !== undefined) {
    apiRef.value.setRowData(newVal);
  }
});

onUnmounted(() => {
  unsubFns.forEach(fn => fn());
  unsubFns = [];
  apiRef.value?.destroy();
  apiRef.value = null;
});

// ─── Expose GridApi to parent ─────────────────────────────────────────────────

defineExpose({ api: apiRef });
</script>

<template>
  <div ref="containerRef" style="width: 100%; height: 100%;" />
</template>

// packages/svelte/src/UltimateGrid.svelte
<!--
  @ultimate-grid/svelte
  Svelte 4 wrapper component for @ultimate-grid/core.

  Usage:
    import UltimateGrid from '@ultimate-grid/svelte';

    <UltimateGrid
      columnDefs={columnDefs}
      rowData={rowData}
      selectionMode="multi"
      rowHeight={36}
      cellRenderer={customCellRenderer}
      onGridReady={(api) => gridApi = api}
      onSortChanged={handleSortChanged}
      onFilterChanged={handleFilterChanged}
      onSelectionChanged={handleSelectionChanged}
    />
-->

<script lang="ts">
  import { onMount, onDestroy, afterUpdate } from 'svelte';
  import { createGrid } from '../../core/src/index.ts';
  import type { RenderPipelineOptions } from '../../core/src/render/RenderPipeline.ts';
  import type {
    ColumnDef,
    GridApi,
    GridOptions,
    GridEventMap,
  } from '../../core/src/types.ts';

  // ─── Props ──────────────────────────────────────────────────────────────────

  export let columnDefs:    ColumnDef[]                                   = [];
  export let rowData:       unknown[]                        | undefined   = undefined;
  export let selectionMode: GridOptions['selectionMode']                   = 'multi';
  export let rowHeight:     number                           | undefined   = undefined;
  export let cellRenderer:  RenderPipelineOptions['cellRenderer'] | undefined = undefined;
  export let options:       Partial<GridOptions>             | undefined   = undefined;

  // ─── Event callbacks ────────────────────────────────────────────────────────

  export let onGridReady:        ((api: GridApi) => void)                               | undefined = undefined;
  export let onRowDataChanged:   ((e: GridEventMap['rowDataChanged'])   => void)        | undefined = undefined;
  export let onSortChanged:      ((e: GridEventMap['sortChanged'])      => void)        | undefined = undefined;
  export let onFilterChanged:    ((e: GridEventMap['filterChanged'])    => void)        | undefined = undefined;
  export let onSelectionChanged: ((e: GridEventMap['selectionChanged']) => void)        | undefined = undefined;
  export let onColumnResized:    ((e: GridEventMap['columnResized'])    => void)        | undefined = undefined;
  export let onColumnMoved:      ((e: GridEventMap['columnMoved'])      => void)        | undefined = undefined;
  export let onCellClicked:      ((e: GridEventMap['cellClicked'])      => void)        | undefined = undefined;
  export let onCellDoubleClicked:((e: GridEventMap['cellDoubleClicked'])=> void)        | undefined = undefined;
  export let onActiveCellChanged: ((e: GridEventMap['activeCellChanged']) => void)        | undefined = undefined;

  // ─── Internal ───────────────────────────────────────────────────────────────

  let containerEl: HTMLDivElement;
  let gridApi: GridApi | null = null;
  let unsubFns: Array<() => void> = [];

  // Track keys for deciding when to remount vs. setRowData
  let _colKey    = '';
  let _rowData   = rowData;

  function getColKey(): string {
    return columnDefs.map(c => c.key).join(',') + ':' + selectionMode + ':' + (rowHeight ?? '');
  }

  function mountGrid(): void {
    if (!containerEl) return;

    unsubFns.forEach(fn => fn());
    unsubFns = [];
    if (gridApi) {
      gridApi.destroy();
      gridApi = null;
    }

    gridApi = createGrid({
      ...options,
      container:     containerEl,
      columnDefs,
      rowData:       rowData ?? [],
      selectionMode: selectionMode ?? options?.selectionMode ?? 'multi',
      rowHeight:     rowHeight ?? options?.rowHeight,
      cellRenderer,
    });

    unsubFns.push(
      gridApi.on('rowDataChanged',    e => onRowDataChanged?.(e)),
      gridApi.on('sortChanged',       e => onSortChanged?.(e)),
      gridApi.on('filterChanged',     e => onFilterChanged?.(e)),
      gridApi.on('selectionChanged',  e => onSelectionChanged?.(e)),
      gridApi.on('columnResized',     e => onColumnResized?.(e)),
      gridApi.on('columnMoved',       e => onColumnMoved?.(e)),
      gridApi.on('cellClicked',       e => onCellClicked?.(e)),
      gridApi.on('cellDoubleClicked', e => onCellDoubleClicked?.(e)),
      gridApi.on('activeCellChanged',  e => onActiveCellChanged?.(e)),
    );

    onGridReady?.(gridApi);
    _colKey  = getColKey();
    _rowData = rowData;
  }

  // ─── Lifecycle ───────────────────────────────────────────────────────────────

  onMount(() => {
    _colKey  = getColKey();
    _rowData = rowData;
    mountGrid();
  });

  afterUpdate(() => {
    const newColKey = getColKey();
    if (newColKey !== _colKey) {
      // Structural change — remount
      _colKey  = newColKey;
      _rowData = rowData;
      mountGrid();
    } else if (gridApi && rowData !== _rowData) {
      // Data-only change — sync without remount
      _rowData = rowData;
      if (rowData !== undefined) {
        gridApi.setRowData(rowData);
      }
    }
  });

  onDestroy(() => {
    unsubFns.forEach(fn => fn());
    unsubFns = [];
    gridApi?.destroy();
    gridApi = null;
  });
</script>

<div bind:this={containerEl} style="width: 100%; height: 100%;" />
