// packages/angular/src/ultimate-grid.component.ts
/**
 * @ultimate-grid/angular
 * Angular 17+ standalone component wrapping @ultimate-grid/core.
 *
 * Usage:
 *   import { UltimateGridComponent } from '@ultimate-grid/angular';
 *
 *   @Component({
 *     imports: [UltimateGridComponent],
 *     template: `
 *       <ultimate-grid
 *         [columnDefs]="columnDefs"
 *         [rowData]="rowData"
 *         selectionMode="multi"
 *         [rowHeight]="36"
 *         [cellRenderer]="customCellRenderer"
 *         (gridReady)="onGridReady($event)"
 *         (sortChanged)="onSortChanged($event)"
 *         (filterChanged)="onFilterChanged($event)"
 *         (selectionChanged)="onSelectionChanged($event)"
 *       />
 *     `,
 *   })
 */

import {
  Component,
  ElementRef,
  Input,
  Output,
  EventEmitter,
  AfterViewInit,
  OnDestroy,
  OnChanges,
  SimpleChanges,
  ViewChild,
  ViewEncapsulation,
} from '@angular/core';
import { createGrid } from '../../core/src/index.ts';
import type { RenderPipelineOptions } from '../../core/src/render/RenderPipeline.ts';
import type {
  ColumnDef,
  GridApi,
  GridOptions,
  GridEventMap,
} from '../../core/src/types.ts';

// ─── Component ────────────────────────────────────────────────────────────────

@Component({
  selector: 'ultimate-grid',
  standalone: true,
  template: `<div #container style="width:100%;height:100%"></div>`,
  encapsulation: ViewEncapsulation.None,
})
export class UltimateGridComponent<TData = unknown>
  implements AfterViewInit, OnDestroy, OnChanges
{
  @ViewChild('container') containerRef!: ElementRef<HTMLDivElement>;

  // ─── Inputs ────────────────────────────────────────────────────────────────

  @Input() columnDefs:    ColumnDef<TData>[]                        = [];
  @Input() rowData?:      TData[];
  @Input() selectionMode?: GridOptions<TData>['selectionMode'];
  @Input() rowHeight?:    number;
  @Input() cellRenderer?: RenderPipelineOptions['cellRenderer'];
  @Input() options?:      Partial<GridOptions<TData>>;

  // ─── Outputs ───────────────────────────────────────────────────────────────

  @Output() gridReady        = new EventEmitter<GridApi<TData>>();
  @Output() rowDataChanged   = new EventEmitter<GridEventMap['rowDataChanged']>();
  @Output() sortChanged      = new EventEmitter<GridEventMap['sortChanged']>();
  @Output() filterChanged    = new EventEmitter<GridEventMap['filterChanged']>();
  @Output() selectionChanged = new EventEmitter<GridEventMap['selectionChanged']>();
  @Output() columnResized    = new EventEmitter<GridEventMap['columnResized']>();
  @Output() columnMoved      = new EventEmitter<GridEventMap['columnMoved']>();
  @Output() cellClicked      = new EventEmitter<GridEventMap['cellClicked']>();
  @Output() cellDoubleClicked= new EventEmitter<GridEventMap['cellDoubleClicked']>();
  @Output() activeCellChanged = new EventEmitter<GridEventMap['activeCellChanged']>();

  // ─── Internal ──────────────────────────────────────────────────────────────

  private api:       GridApi<TData> | null = null;
  private unsubFns:  Array<() => void>     = [];

  // ─── Lifecycle ─────────────────────────────────────────────────────────────

  ngAfterViewInit(): void {
    this.mountGrid();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!this.api) return; // Not yet mounted

    const structural = changes['columnDefs'] || changes['selectionMode'] || changes['rowHeight'];
    if (structural) {
      this.mountGrid();
    } else if (changes['rowData']) {
      this.api.setRowData(this.rowData ?? []);
    }
  }

  ngOnDestroy(): void {
    this.cleanup();
  }

  // ─── Public ────────────────────────────────────────────────────────────────

  getApi(): GridApi<TData> | null {
    return this.api;
  }

  // ─── Private ───────────────────────────────────────────────────────────────

  private mountGrid(): void {
    if (!this.containerRef?.nativeElement) return;

    this.cleanup();

    this.api = createGrid<TData>({
      ...this.options,
      container:     this.containerRef.nativeElement,
      columnDefs:    this.columnDefs,
      rowData:       this.rowData ?? [],
      selectionMode: this.selectionMode ?? this.options?.selectionMode ?? 'multi',
      rowHeight:     this.rowHeight ?? this.options?.rowHeight,
      cellRenderer:  this.cellRenderer,
    });

    this.unsubFns.push(
      this.api.on('rowDataChanged',    e => this.rowDataChanged.emit(e)),
      this.api.on('sortChanged',       e => this.sortChanged.emit(e)),
      this.api.on('filterChanged',     e => this.filterChanged.emit(e)),
      this.api.on('selectionChanged',  e => this.selectionChanged.emit(e)),
      this.api.on('columnResized',     e => this.columnResized.emit(e)),
      this.api.on('columnMoved',       e => this.columnMoved.emit(e)),
      this.api.on('cellClicked',       e => this.cellClicked.emit(e)),
      this.api.on('cellDoubleClicked', e => this.cellDoubleClicked.emit(e)),
      this.api.on('activeCellChanged',  e => this.activeCellChanged.emit(e)),
    );

    this.gridReady.emit(this.api);
  }

  private cleanup(): void {
    this.unsubFns.forEach(fn => fn());
    this.unsubFns = [];
    if (this.api) {
      this.api.destroy();
      this.api = null;
    }
  }
}

// packages/svelte/src/UltimateGrid.svelte
<!--
  @ultimate-grid/svelte
  Svelte 4 wrapper component for @ultimate-grid/core.

  Usage:
    import UltimateGrid from '@ultimate-grid/svelte';

    <UltimateGrid
      columnDefs={columnDefs}
      rowData={rowData}
      selectionMode="multi"
      rowHeight={36}
      cellRenderer={customCellRenderer}
      onGridReady={(api) => gridApi = api}
      onSortChanged={handleSortChanged}
      onFilterChanged={handleFilterChanged}
      onSelectionChanged={handleSelectionChanged}
    />
-->

<script lang="ts">
  import { onMount, onDestroy, afterUpdate } from 'svelte';
  import { createGrid } from '../../core/src/index.ts';
  import type { RenderPipelineOptions } from '../../core/src/render/RenderPipeline.ts';
  import type {
    ColumnDef,
    GridApi,
    GridOptions,
    GridEventMap,
  } from '../../core/src/types.ts';

  // ─── Props ──────────────────────────────────────────────────────────────────

  export let columnDefs:    ColumnDef[]                                   = [];
  export let rowData:       unknown[]                        | undefined   = undefined;
  export let selectionMode: GridOptions['selectionMode']                   = 'multi';
  export let rowHeight:     number                           | undefined   = undefined;
  export let cellRenderer:  RenderPipelineOptions['cellRenderer'] | undefined = undefined;
  export let options:       Partial<GridOptions>             | undefined   = undefined;

  // ─── Event callbacks ────────────────────────────────────────────────────────

  export let onGridReady:        ((api: GridApi) => void)                               | undefined = undefined;
  export let onRowDataChanged:   ((e: GridEventMap['rowDataChanged'])   => void)        | undefined = undefined;
  export let onSortChanged:      ((e: GridEventMap['sortChanged'])      => void)        | undefined = undefined;
  export let onFilterChanged:    ((e: GridEventMap['filterChanged'])    => void)        | undefined = undefined;
  export let onSelectionChanged: ((e: GridEventMap['selectionChanged']) => void)        | undefined = undefined;
  export let onColumnResized:    ((e: GridEventMap['columnResized'])    => void)        | undefined = undefined;
  export let onColumnMoved:      ((e: GridEventMap['columnMoved'])      => void)        | undefined = undefined;
  export let onCellClicked:      ((e: GridEventMap['cellClicked'])      => void)        | undefined = undefined;
  export let onCellDoubleClicked:((e: GridEventMap['cellDoubleClicked'])=> void)        | undefined = undefined;
  export let onActiveCellChanged: ((e: GridEventMap['activeCellChanged']) => void)        | undefined = undefined;

  // ─── Internal ───────────────────────────────────────────────────────────────

  let containerEl: HTMLDivElement;
  let gridApi: GridApi | null = null;
  let unsubFns: Array<() => void> = [];

  // Track keys for deciding when to remount vs. setRowData
  let _colKey    = '';
  let _rowData   = rowData;

  function getColKey(): string {
    return columnDefs.map(c => c.key).join(',') + ':' + selectionMode + ':' + (rowHeight ?? '');
  }

  function mountGrid(): void {
    if (!containerEl) return;

    unsubFns.forEach(fn => fn());
    unsubFns = [];
    if (gridApi) {
      gridApi.destroy();
      gridApi = null;
    }

    gridApi = createGrid({
      ...options,
      container:     containerEl,
      columnDefs,
      rowData:       rowData ?? [],
      selectionMode: selectionMode ?? options?.selectionMode ?? 'multi',
      rowHeight:     rowHeight ?? options?.rowHeight,
      cellRenderer,
    });

    unsubFns.push(
      gridApi.on('rowDataChanged',    e => onRowDataChanged?.(e)),
      gridApi.on('sortChanged',       e => onSortChanged?.(e)),
      gridApi.on('filterChanged',     e => onFilterChanged?.(e)),
      gridApi.on('selectionChanged',  e => onSelectionChanged?.(e)),
      gridApi.on('columnResized',     e => onColumnResized?.(e)),
      gridApi.on('columnMoved',       e => onColumnMoved?.(e)),
      gridApi.on('cellClicked',       e => onCellClicked?.(e)),
      gridApi.on('cellDoubleClicked', e => onCellDoubleClicked?.(e)),
      gridApi.on('activeCellChanged',  e => onActiveCellChanged?.(e)),
    );

    onGridReady?.(gridApi);
    _colKey  = getColKey();
    _rowData = rowData;
  }

  // ─── Lifecycle ───────────────────────────────────────────────────────────────

  onMount(() => {
    _colKey  = getColKey();
    _rowData = rowData;
    mountGrid();
  });

  afterUpdate(() => {
    const newColKey = getColKey();
    if (newColKey !== _colKey) {
      // Structural change — remount
      _colKey  = newColKey;
      _rowData = rowData;
      mountGrid();
    } else if (gridApi && rowData !== _rowData) {
      // Data-only change — sync without remount
      _rowData = rowData;
      if (rowData !== undefined) {
        gridApi.setRowData(rowData);
      }
    }
  });

  onDestroy(() => {
    unsubFns.forEach(fn => fn());
    unsubFns = [];
    gridApi?.destroy();
    gridApi = null;
  });
</script>

<div bind:this={containerEl} style="width: 100%; height: 100%;" />
